{% set name = "apache-airflow-providers-apache-hdfs" %}
{% set version = "4.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_hdfs-{{ version }}.tar.gz
  sha256: 3795c54a5bf0d34751cd888d3a5f427343818fe70713d8f8c7ad618897163442

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.6.0
    - python-hdfs >=2.0.4

test:
  imports:
    - airflow.providers.apache.hdfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-hdfs for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/hdfs/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hdfs/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
